# Generated by Django 4.1.5 on 2023-01-24 19:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transacoes_loja",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tipo", models.CharField(max_length=1)),
                ("data", models.CharField(max_length=10)),
                ("valor", models.FloatField()),
                ("cpf", models.CharField(max_length=11)),
                ("cartao", models.CharField(max_length=12)),
                ("hora", models.CharField(max_length=8)),
                ("dono_da_loja", models.CharField(max_length=15)),
                ("nome_loja", models.CharField(max_length=19)),
            ],
        ),
    ]
